import { YearLevel, TimetableCategory, TimetableBlock, StudentCohortRecord, TeacherRecord } from '../types';

export const THEME = {
  purple: {
    primary: '#4A154B',
    dark: '#350B36',
    deep: '#260627',
    light: '#6E2570',
    subtle: '#FAF3FA',
    border: '#E8CEE8',
  },
  gold: {
    primary: '#D4AF37',
    rich: '#E5A93C',
    amber: '#C59A27',
    light: '#FBF5E6',
    border: '#F2DDA4',
  }
};

// Comprehensive Glennie curriculum subjects by Year Level based on Assessment Calendars
export const YEAR_LEVEL_SUBJECTS: Record<YearLevel, string[]> = {
  7: [
    'The Arts',
    'English',
    'French',
    'Français - French Immersion',
    'Humanities and Social Science (HASS)',
    'Histoire et Géographie - French Immersion',
    'Health and Physical Education (HPE)',
    'Mathematics',
    'Mathématiques - French Immersion',
    'Science',
    'Science - French Immersion',
    'Technology',
  ],
  8: [
    'The Arts',
    'English',
    'French',
    'Français - French Immersion',
    'Humanities and Social Science (HASS)',
    'Histoire et Géographie - French Immersion',
    'Health and Physical Education (HPE)',
    'Mathematics',
    'Mathématiques - French Immersion',
    'Science',
    'Technology',
  ],
  9: [
    'Civics and Citizenship',
    'Commerce',
    'The Arts - Drama',
    'Digital Technologies',
    'English',
    'French',
    'Français - French Immersion',
    'Design - Food Technologies',
    'Humanities and Social Science (HASS)',
    'Histoire et Géographie - French Immersion',
    'Health and Physical Education (HPE)',
    'Mathematics',
    'On the Money',
    'Science',
    'The Arts - Visual Arts',
  ],
  10: [
    'Agricultural Science',
    'Curious Minds: Science and Mathematics Elective',
    'Design',
    'English',
    'French',
    'French - Year 11 Course',
    'Geography',
    'History (The Ancient Years)',
    'History - The Modern World',
    'Hospitality',
    'Certificate II in Health Support Services',
    'Mathematics',
    'The Arts - Music',
    'Physical Education',
    'Science',
    'Science - Extension',
    'Science - Foundations',
    'Sport, Fitness and Recreation',
    'The Arts - Visual Arts',
  ],
  11: [
    'Ancient History',
    'Agricultural Science',
    'Biology',
    'Certificate III in Business',
    'Chemistry',
    'Diploma in Business',
    'Design',
    'Economics',
    'English',
    'Essential English',
    'English and Literature Extension',
    'Literature',
    'Essential Mathematics',
    'Mathematics - General',
    'Mathematics - Mathematical Methods',
    'Specialist Mathematics',
    'French - Year 12 Course',
    'Geography',
    'Health',
    'Hospitality',
    'Certificate III in Health Services Assistance',
    'Legal Studies',
    'Modern History',
    'Music',
    'Music Extension',
    'Physical Education',
    'Physics',
    'Philosophy and Reason',
    'Certificate III in Fitness / Sport and Rec',
    'Visual Art',
    'Visual Arts in Practice',
  ],
  // Year 12 subjects are identical to Year 11
  12: [
    'Ancient History',
    'Agricultural Science',
    'Biology',
    'Certificate III in Business',
    'Chemistry',
    'Diploma in Business',
    'Design',
    'Economics',
    'English',
    'Essential English',
    'English and Literature Extension',
    'Literature',
    'Essential Mathematics',
    'Mathematics - General',
    'Mathematics - Mathematical Methods',
    'Specialist Mathematics',
    'French - Year 12 Course',
    'Geography',
    'Health',
    'Hospitality',
    'Certificate III in Health Services Assistance',
    'Legal Studies',
    'Modern History',
    'Music',
    'Music Extension',
    'Physical Education',
    'Physics',
    'Philosophy and Reason',
    'Certificate III in Fitness / Sport and Rec',
    'Visual Art',
    'Visual Arts in Practice',
  ],
};

export function getSubjectsForYear(yearLevel?: YearLevel): string[] {
  if (!yearLevel) return YEAR_LEVEL_SUBJECTS[10];
  return YEAR_LEVEL_SUBJECTS[yearLevel] || YEAR_LEVEL_SUBJECTS[10];
}

// Fallback all secondary subjects list
export const SECONDARY_SUBJECTS: string[] = YEAR_LEVEL_SUBJECTS[11];

export const TIMETABLE_CATEGORY_CONFIG: Record<TimetableCategory, {
  label: string;
  bg: string;
  border: string;
  text: string;
  badge: string;
}> = {
  'Study': {
    label: 'Study Session',
    bg: 'bg-amber-100 hover:bg-amber-200',
    border: 'border-l-4 border-amber-500',
    text: 'text-amber-950 font-semibold',
    badge: 'bg-amber-500 text-white',
  },
  'School': {
    label: 'School Timetable',
    bg: 'bg-purple-900/10 hover:bg-purple-900/15',
    border: 'border-l-4 border-[#4A154B]',
    text: 'text-[#4A154B] font-semibold',
    badge: 'bg-[#4A154B] text-white',
  },
  'Sport / Training': {
    label: 'Sport & Training',
    bg: 'bg-emerald-100 hover:bg-emerald-200',
    border: 'border-l-4 border-emerald-600',
    text: 'text-emerald-950 font-semibold',
    badge: 'bg-emerald-600 text-white',
  },
  'Work': {
    label: 'Part-Time Work / Chores',
    bg: 'bg-blue-100 hover:bg-blue-200',
    border: 'border-l-4 border-blue-600',
    text: 'text-blue-950 font-semibold',
    badge: 'bg-blue-600 text-white',
  },
  'Sleep / Wellbeing': {
    label: 'Sleep & Wellbeing',
    bg: 'bg-indigo-100 hover:bg-indigo-200',
    border: 'border-l-4 border-indigo-600',
    text: 'text-indigo-950 font-semibold',
    badge: 'bg-indigo-600 text-white',
  },
  'Personal': {
    label: 'Personal & Family',
    bg: 'bg-slate-100 hover:bg-slate-200',
    border: 'border-l-4 border-slate-500',
    text: 'text-slate-800 font-semibold',
    badge: 'bg-slate-600 text-white',
  },
};

export const DEFAULT_SCHOOL_DAY_BLOCKS: Omit<TimetableBlock, 'id'>[] = [
  { day: 'Monday', startTime: '08:30', endTime: '15:15', title: 'School Hours & Classes', category: 'School' },
  { day: 'Tuesday', startTime: '08:30', endTime: '15:15', title: 'School Hours & Classes', category: 'School' },
  { day: 'Wednesday', startTime: '08:30', endTime: '15:15', title: 'School Hours & Classes', category: 'School' },
  { day: 'Thursday', startTime: '08:30', endTime: '15:15', title: 'School Hours & Classes', category: 'School' },
  { day: 'Friday', startTime: '08:30', endTime: '15:15', title: 'School Hours & Classes', category: 'School' },
];

export const DEFAULT_TIMETABLE_SAMPLE: TimetableBlock[] = [
  { id: 'b-1', day: 'Monday', startTime: '08:30', endTime: '15:15', title: 'School Classes (Glennie)', category: 'School' },
  { id: 'b-2', day: 'Monday', startTime: '16:00', endTime: '17:30', title: 'Mathematics - Practice Problems', category: 'Study', subject: 'Mathematics' },
  { id: 'b-3', day: 'Monday', startTime: '19:00', endTime: '20:15', title: 'Science - Topic Review', category: 'Study', subject: 'Science' },
  
  { id: 'b-4', day: 'Tuesday', startTime: '07:00', endTime: '08:00', title: 'Morning Swimming / Fitness', category: 'Sport / Training' },
  { id: 'b-5', day: 'Tuesday', startTime: '08:30', endTime: '15:15', title: 'School Classes (Glennie)', category: 'School' },
  { id: 'b-6', day: 'Tuesday', startTime: '16:00', endTime: '17:30', title: 'English - Reading & Drafting', category: 'Study', subject: 'English' },
  { id: 'b-7', day: 'Tuesday', startTime: '19:00', endTime: '20:00', title: 'History / HASS - Inquiry Notes', category: 'Study', subject: 'History' },

  { id: 'b-8', day: 'Wednesday', startTime: '08:30', endTime: '15:15', title: 'School Classes (Glennie)', category: 'School' },
  { id: 'b-9', day: 'Wednesday', startTime: '16:00', endTime: '17:15', title: 'Languages / French Practice', category: 'Study', subject: 'French' },
  { id: 'b-10', day: 'Wednesday', startTime: '18:00', endTime: '19:30', title: 'Music Rehearsal / Band', category: 'Personal' },

  { id: 'b-11', day: 'Thursday', startTime: '08:30', endTime: '15:15', title: 'School Classes (Glennie)', category: 'School' },
  { id: 'b-12', day: 'Thursday', startTime: '16:00', endTime: '17:30', title: 'Science - Lab Experiment Writeup', category: 'Study', subject: 'Science' },
  { id: 'b-13', day: 'Thursday', startTime: '19:00', endTime: '20:15', title: 'Mathematics - Worked Examples', category: 'Study', subject: 'Mathematics' },

  { id: 'b-14', day: 'Friday', startTime: '08:30', endTime: '15:15', title: 'School Classes (Glennie)', category: 'School' },
  { id: 'b-15', day: 'Friday', startTime: '16:00', endTime: '17:00', title: 'Weekly Recap & Organization', category: 'Study', subject: 'English' },
  { id: 'b-16', day: 'Friday', startTime: '18:00', endTime: '20:00', title: 'Family & Wellbeing Dinner', category: 'Personal' },

  { id: 'b-17', day: 'Saturday', startTime: '08:30', endTime: '10:30', title: 'Club / School Sport Fixture', category: 'Sport / Training' },
  { id: 'b-18', day: 'Saturday', startTime: '13:30', endTime: '15:00', title: 'Mathematics - Revision Set', category: 'Study', subject: 'Mathematics' },

  { id: 'b-19', day: 'Sunday', startTime: '10:00', endTime: '11:30', title: 'English - Essay Planning', category: 'Study', subject: 'English' },
  { id: 'b-20', day: 'Sunday', startTime: '19:30', endTime: '20:30', title: 'Weekly Planner Review & Pack Bag', category: 'Sleep / Wellbeing' },
];

export const DEMO_COHORT_STUDENTS: StudentCohortRecord[] = [
  {
    user: {
      uid: 'student-yr12-radhika',
      name: 'Radhika Kumar',
      email: 'radhika.k@glennie.qld.edu.au',
      yearLevel: 12,
      weeklyGoal: 25,
      role: 'student',
      enrolledSubjects: ['Mathematical Methods', 'Specialist Mathematics', 'Chemistry', 'Physics', 'English'],
    },
    totalHoursThisWeek: 26.5,
    goalHours: 25,
    percentAchieved: 106,
    status: 'On Track',
    recentSubject: 'Chemistry',
    logsCount: 18,
    logs: [],
    timetableBlocks: DEFAULT_TIMETABLE_SAMPLE,
  },
  {
    user: {
      uid: 'student-yr11-charlotte',
      name: 'Charlotte Webb',
      email: 'charlotte.w@glennie.qld.edu.au',
      yearLevel: 11,
      weeklyGoal: 20,
      role: 'student',
      enrolledSubjects: ['Mathematical Methods', 'Physics', 'Chemistry', 'English', 'Design Technologies'],
    },
    totalHoursThisWeek: 21.0,
    goalHours: 20,
    percentAchieved: 105,
    status: 'On Track',
    recentSubject: 'Physics',
    logsCount: 14,
    logs: [],
    timetableBlocks: DEFAULT_TIMETABLE_SAMPLE,
  },
  {
    user: {
      uid: 'student-yr10-maya',
      name: 'Maya Henderson',
      email: 'maya.h@glennie.qld.edu.au',
      yearLevel: 10,
      weeklyGoal: 15,
      role: 'student',
      enrolledSubjects: ['Mathematics', 'Science', 'English', 'History', 'Visual Art'],
    },
    totalHoursThisWeek: 15.5,
    goalHours: 15,
    percentAchieved: 103,
    status: 'On Track',
    recentSubject: 'Science',
    logsCount: 11,
    logs: [],
    timetableBlocks: DEFAULT_TIMETABLE_SAMPLE,
  },
  {
    user: {
      uid: 'student-yr9-sophie',
      name: 'Sophie Campbell',
      email: 'sophie.c@glennie.qld.edu.au',
      yearLevel: 9,
      weeklyGoal: 10,
      role: 'student',
      enrolledSubjects: ['English', 'Mathematics', 'Science', 'Humanities / HASS', 'French'],
    },
    totalHoursThisWeek: 10.5,
    goalHours: 10,
    percentAchieved: 105,
    status: 'On Track',
    recentSubject: 'Mathematics',
    logsCount: 8,
    logs: [],
    timetableBlocks: DEFAULT_TIMETABLE_SAMPLE,
  },
  {
    user: {
      uid: 'student-yr8-olivia',
      name: 'Olivia Zhang',
      email: 'olivia.z@glennie.qld.edu.au',
      yearLevel: 8,
      weeklyGoal: 10,
      role: 'student',
      enrolledSubjects: ['English', 'Mathematics', 'Science', 'Geography', 'Drama'],
    },
    totalHoursThisWeek: 8.5,
    goalHours: 10,
    percentAchieved: 85,
    status: 'Near Target',
    recentSubject: 'English',
    logsCount: 7,
    logs: [],
    timetableBlocks: DEFAULT_TIMETABLE_SAMPLE,
  },
  {
    user: {
      uid: 'student-yr7-isla',
      name: 'Isla Thompson',
      email: 'isla.t@glennie.qld.edu.au',
      yearLevel: 7,
      weeklyGoal: 5,
      role: 'student',
      enrolledSubjects: ['English', 'Mathematics', 'Science', 'Humanities / HASS', 'Music'],
    },
    totalHoursThisWeek: 5.5,
    goalHours: 5,
    percentAchieved: 110,
    status: 'On Track',
    recentSubject: 'Science',
    logsCount: 5,
    logs: [],
    timetableBlocks: DEFAULT_TIMETABLE_SAMPLE,
  },
  {
    user: {
      uid: 'student-yr10-lucas',
      name: 'Lucas Campbell',
      email: 'lucas.c@glennie.qld.edu.au',
      yearLevel: 10,
      weeklyGoal: 15,
      role: 'student',
      enrolledSubjects: ['Mathematics', 'Science', 'English', 'Business', 'Digital Technologies'],
    },
    totalHoursThisWeek: 7.5,
    goalHours: 15,
    percentAchieved: 50,
    status: 'Needs Support',
    recentSubject: 'Mathematics',
    logsCount: 4,
    logs: [],
    timetableBlocks: DEFAULT_TIMETABLE_SAMPLE,
  },
  {
    user: {
      uid: 'student-yr7-mia',
      name: 'Mia Fitzgerald',
      email: 'mia.f@glennie.qld.edu.au',
      yearLevel: 7,
      weeklyGoal: 5,
      role: 'student',
      enrolledSubjects: ['English', 'Mathematics', 'Science', 'Art', 'PE'],
    },
    totalHoursThisWeek: 2.5,
    goalHours: 5,
    percentAchieved: 50,
    status: 'Needs Support',
    recentSubject: 'English',
    logsCount: 2,
    logs: [],
    timetableBlocks: DEFAULT_TIMETABLE_SAMPLE,
  }
];

// Initial teacher roles configured in the school system
export const DEFAULT_TEACHERS: TeacherRecord[] = [
  {
    id: 'teacher-yr7-clarke',
    name: 'Mrs. Rebecca Clarke',
    email: 'clarker@glennie.qld.edu.au',
    assignedYearLevels: [7],
    title: 'Year 7 Middle Years Coordinator',
    addedAt: '2026-01-15T08:00:00.000Z',
  },
  {
    id: 'teacher-yr89-campbell',
    name: 'Mr. Marcus Campbell',
    email: 'campbellm@glennie.qld.edu.au',
    assignedYearLevels: [8, 9],
    title: 'Years 8 & 9 Academic Care Leader',
    addedAt: '2026-02-01T08:00:00.000Z',
  },
  {
    id: 'teacher-yr10-wilson',
    name: 'Ms. Elizabeth Wilson',
    email: 'wilsone@glennie.qld.edu.au',
    assignedYearLevels: [10],
    title: 'Year 10 Senior Transition Leader',
    addedAt: '2026-02-10T08:00:00.000Z',
  },
  {
    id: 'teacher-yr1112-shearer',
    name: 'Mr. Andrew Henderson',
    email: 'hendersona@glennie.qld.edu.au',
    assignedYearLevels: [11, 12],
    title: 'Senior School QCE Coordinator',
    addedAt: '2026-01-20T08:00:00.000Z',
  },
];

// Comprehensive pedagogical background & rationale for Path to Potential
export const EDUCATIONAL_RATIONALE = {
  title: 'Path to Potential: Academic Framework & Pedagogical Rationale',
  subtitle: 'A Research-Informed Model for Developing Self-Regulated Scholars from Year 7 to Year 12',
  corePillars: [
    {
      title: 'Graduated Study Benchmarks',
      description: 'Cognitive maturity, assessment weightings, and syllabus volume expand progressively from Middle School to Senior Secondary. Study time builds incrementally: Year 7 (5 hrs/wk), Years 8–9 (10 hrs/wk), Year 10 (15 hrs/wk), Year 11 (20 hrs/wk), and Year 12 (25 hrs/wk).',
      evidence: 'Aligned with Australian Curriculum and QCAA senior syllabus workload expectations (QCE Units 1-4).',
    },
    {
      title: 'Spaced Retrieval vs Cramming',
      description: 'Cramming produces short-term familiarity with rapid decay. Spaced distribution of short study sessions across 5 to 7 days consolidates neural pathways and elevates long-term recall by up to 200%.',
      evidence: 'Rooted in Ebbinghaus’s Forgetting Curve and Cepeda et al.’s spacing effect meta-analyses.',
    },
    {
      title: 'Self-Regulated Learning (SRL)',
      description: 'Success in tertiary and professional life relies on self-regulation. Students move through a three-stage cycle: Forethought (timetabling and goal setting), Performance (focused timed study blocks), and Self-Reflection (weekly logs and progress review).',
      evidence: 'Barry Zimmerman’s Self-Regulated Learning Model and John Hattie’s Visible Learning research.',
    },
    {
      title: 'Deliberate Practice & Habit Stacking',
      description: 'Time spent in passive reading yields minimal retention. Dedicated study blocks prompt deliberate practice—solving unfamiliar problems, drafting arguments, and timed past paper practice.',
      evidence: 'K. Anders Ericsson’s deliberate practice framework.',
    },
    {
      title: 'Holistic Wellbeing & Sleep Protection',
      description: 'Academic excellence cannot come at the expense of health. The Path to Potential timetable mandates explicit blocks for 8–9 hours of sleep, co-curricular sport, family dinner, and downtime. Without cognitive recovery, study efficiency declines.',
      evidence: 'Neuroscience of memory consolidation during slow-wave and REM sleep (Walker, 2017).',
    },
  ],
  benchmarks: [
    {
      year: 7,
      hours: 5,
      focus: 'Habit Formation & Transition',
      detail: 'Establishing daily 45-minute homework and review routines. Learning how to organize folders, review class notes, and break projects into manageable steps.',
    },
    {
      year: 8,
      hours: 10,
      focus: 'Active Recall & Foundation Mastery',
      detail: 'Moving beyond passive reading. Developing flashcards, summary sheets, and structured problem-solving routines across English, Maths, Science, and HASS.',
    },
    {
      year: 9,
      hours: 10,
      focus: 'Inquiry Depth & Elective Independence',
      detail: 'Deepening analytical writing, sustained inquiry, and project management in preparation for senior elective pathways.',
    },
    {
      year: 10,
      hours: 15,
      focus: 'Senior Secondary Transition & QCE Readiness',
      detail: 'Simulating senior assessment conditions. Practicing extended analytical essays, research investigations, and complex mathematical problem solving.',
    },
    {
      year: 11,
      hours: 20,
      focus: 'QCE Units 1 & 2 Syllabus Rigour',
      detail: 'Navigating formative IA1 and IA2 assessment milestones. Balancing 5–6 ATAR or Applied subjects with consistent weekly review blocks.',
    },
    {
      year: 12,
      hours: 25,
      focus: 'QCE Units 3 & 4 Mastery & External Exam Preparation',
      detail: 'Peak academic consolidation. Timed external exam papers, syllabus criterion mastery, and deep conceptual synoptic problem solving.',
    },
  ],
};
